environment: 
  mq:
    host: localhost
    port: 1414
    queue-manager: QM1
    channel: TO.QM1
    username: mqm
    password: 
    receive-timeout: 2000
    queues:
      billing-queue: BILLING.IN.QUEUE
      datastream-queue: DATASTREAM.IN.QUEUE